### ISSUE TITLE
Limit Blog/any page's posts but allow for infinite scrolling or separate blogs into pages.

### ISSUE THREAD

**Issue by Nasafato** [SEL-Columbia/SEL-Columbia.github.io#17]
So there're a lot of blog posts and project posts. We don't always want to display all of them at once, because it's inefficient to load everything just to view the most recent 5. The Bedford Lab page limits the blog posts to 8, so I've decided to do the same for now. This is easily accomplished by using the loop `{% for post in site.categories.blog limit: 8%}` (remember that all posts in `blog/_posts` are technically under `site.categories.blog`, so this is a more specific way of looping through only blog posts without using conditionals to test if the post is of the blog category.

The Bedford Page allows for infinite scrolling, however. I'm not sure whether this requires a plug-in (which means we won't be able to use it) or just your everyday AJAX requests to populate it.

**Comment by chrisnatali** [comment]
Not sure we want to use the bedford.io solution (a js pagination lib that seems to be out of support).  I think it's ok to use certain standard plugins.  Seems like jekyll-paginate is supported by gh-pages, so I'd suggest going with that.  See list of gems [here](https://pages.github.com/versions/)

**Comment by vr2262** [comment]
@chrisnatali @Nasafato 

So after banging my head against this for quite some time it looks like this isn't actually possible with the pagination plugin.

The Jekyll pagination plugin is extremely blunt. It can only loop over all posts, regardless of category. In other words, you get `projects`, `blog`, and `publications` (and so on) posts all mixed together.

Down the line, Jekyll might include something more flexible...

For now I'm looking into doing this without a plugin.

**Comment by vr2262** [comment]
@chrisnatali @Nasafato @ssilwal 

It looks like the least intrusive plugin-free solution is this one: https://talk.jekyllrb.com/t/pagination-on-github-pages-without-plugins/1175

This involves creating each individual page of the blog index manually... I'm going to say that's a non-starter.

So our options are:

1. Give up on pagination (or at least wait for Jekyll to do it properly).
2. Give up on GitHub's auto-build (so we would build the site locally and upload the result).
3. Use a JavaScript solution.
4. Use https://surge.sh/ instead of GitHub pages.

I don't really like any of these options, but I can't think of any others.

I'll hold off on giving my own opinion until I've heard from all of you.

**Comment by vr2262** [comment]
@chrisnatali @Nasafato @ssilwal 

Actually I came up with another option which is... a weird one.

The reason this is a problem at all is that Jekyll (as it is) assumes you are making a blog with posts, not a site with multiple sections.

GitHub pages will serve `user/repo` at `http://user.github.io/repo` even if `user/user.github.io` exists.

So we could have a repository for each section of the site, and then the Jekyll-paginate plugin will work fine, since all the other posts will be in totally separate repositories.

Thoughts?

**Comment by chrisnatali** [comment]
Thoughts generated from a look at bedford.io site  [repo here](https://github.com/blab/blotter):  
1.  Create a tabbed page with one tab ("timeline" view) showing the more detailed post as they are now (limit to 10 posts), the other tab ("index" view) has one or 2 lined post title and link (shows all posts).  

2.  Use bedford.io's [infinite-scroll](https://github.com/blab/blotter/blob/master/js/infinite-scroll.js) solution.

**Comment by vr2262** [comment]
@chrisnatali @Nasafato @ssilwal 

After some discussion with Chris we have decided on this solution:

- `/blog` will show the *n* most recent post summaries, for some *n* (probably 8 or 10), and will include a link to `/blog/archive`.
- `/blog/archive` will show **all post titles** (along with some other metadata) but no summaries.

In other words, forget pagination.

This solution is dead simple to implement without really losing any functionality. Down the line if Jekyll/Github Pages get pagination working properly we can do that instead.

I'm closing this issue in favor of #64
